name: meditation
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.1.1+1
  get: ^4.3.8
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5


  cupertino_icons: ^1.0.2

dev_dependencies:

    flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path : "assets/images/froshlogo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/
    - assets/pics/bgabout.png
    - assets/images/
    - assets/images/Core/


